#Puerto solicitado
server.port=8500

#Nombre de la aplicación
spring.application.name=eurekaServer

# Como este es el servidor, le decimos que no se registre a sí mismo ni busque a otros
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuración del servidor
eureka.instance.hostname=localhost
