spring.application.name=reservas
server.port=8501
springdoc.api-docs-path=/api-reservas
spring.datasource.url=jdbc:mysql://localhost:3306/reservasProyecto?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=abc123.
spring.jpa.hibernate.ddl-auto=validate
