spring.application.name=comentarios
server.port=8503

spring.data.mongodb.uri=mongodb://localhost:27017/comentariosProyecto

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/comentarios

eureka.client.service-url.defaultZone=http://localhost:8500/eureka/

# Forzar manualmente la IP, el nombre de host y el ID de registro
eureka.instance.hostname=127.0.0.1
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=127.0.0.1:comentarios:8503